@startuml
left to right direction

[*] -down-> ローディング中
    ローディング中 -down-> 読み込みエラー : ポケモン一覧取得失敗
    読み込みエラー -down-> ローディング中 : 再読み込み

state ポケモン一覧取得済 {
    ローディング中 -down-> 読み込み済 : 読み込み完了
    読み込み済 -down-> 追加読み込み中 : 追加読み込み
    追加読み込み中 -down-> 追加読み込みエラー : ポケモン一覧取得失敗
    追加読み込みエラー -down-> 追加読み込み中 : 再読み込み実施
    追加読み込み中 -down-> 読み込み済 : 追加読み込み完了
}

ポケモン一覧取得済 --> [*] : タップでポケモン詳細画面へ

@enduml